# Uncomment if needed
# [tool.pytest.ini_options]
# testpaths = [
#     "tests",
# ]

[build-system]
requires = ["setuptools>=77", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "g2rins"
description = "Implementation of G2RINS, a line-and-graph representation of polymers. Grammar validation, generative graph construction, and molecular ensemble generation."
authors = [
  { name = "Gervasio Zaldivar", email = "g.zaldivar@nyu.edu" },
  { name = "Yuan Tian", email = "yuan.tian@nyu.edu" },
]
license = "GPL-3.0-only"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
  "scipy",
  "numpy",
  "networkx",
  "matplotlib",
  "rdkit",
  "lark",
  "typing_extensions",
]
dynamic = ["version"]
readme = "README.md"

[project.optional-dependencies]
test = ["pytest"]

[project.urls]
Homepage = "https://github.com/depablolab/g2rins"
Repository = "https://github.com/depablolab/g2rins"

[tool.setuptools_scm]
version_file = "src/g2rins/_version.py"

[tool.black]
line-length = 196

[tool.coverage.run]
omit = [
  "*/__init__.py",
  "path_to_exclude/*",
  "tests/*",
  "*/_pytest/*",
  "*/more_itertools/*",
  "*/pluggy/*",
  "*/py/*",
  "*/six.py",
]

[tool.setuptools.package-data]
g2rins = ["data/g2rins.lark"]
